### ISSUE TITLE
Attempted an upgrade (TW to Aeon) but it didn't work

### ISSUE THREAD

**Issue by kpbearfl** [sysrich/tik#22]
It starts, it offers to backup my data, it asks to select which disk I want to use for the OS, it begins to back up, and then it stops with a series of errors. Log enclosed.
[tik.log](https://github.com/sysrich/tik/files/15480396/tik.log)

**Comment by sysrich** [comment]
This log is incomplete as it only shows activity from the post imaging module

None of the disk selection or other steps you described are in this log

Please provide the complete log, not just an editing snippit

**Comment by kpbearfl** [comment]
I don’t know what to tell you, see if the photos I took of the screen can help, otherwise please remove the whole “issue” and I’ll wait for the final version release, thank you all for the great work. 

![IMG_5980](https://github.com/sysrich/tik/assets/72484132/a054dc29-a36b-4822-a8ca-8c49185abae7)
![IMG_5981](https://github.com/sysrich/tik/assets/72484132/7bef8f5e-9bd6-45d3-bcd1-29200cd5489b)
![IMG_5982](https://github.com/sysrich/tik/assets/72484132/2556b068-2c22-48a0-a4fe-b03ea8c75dc8)
![IMG_5983](https://github.com/sysrich/tik/assets/72484132/7d61956b-d75d-4ed4-a9c1-3ac1b587101a)
![IMG_5984](https://github.com/sysrich/tik/assets/72484132/d08ca5d1-b776-446e-95ab-092ce2350981)

**Comment by sysrich** [comment]
Those are all screenshots from AFTER the imaging has happened

You described a situation where the errors happened BEFORE the imaging happened

The screenshots match the logs, they all occur AFTER imaging has occured

But I need the logs from the whole process, not just the imaging after the fact.

How did you create your USB Stick?

**Comment by sysrich** [comment]
No resposne, assumed addressed by v1.0.7 or later
