### ISSUE TITLE
AC Detection inconsistant

### ISSUE THREAD

**Issue by sysrich** [sysrich/tik#26]
As discovered in  https://bugzilla.opensuse.org/show_bug.cgi?id=1225544, we need to find a more sensible approach

Current working theory is discussed here: https://t.me/openSUSE_Aeon/47940

**Comment by piyr9** [comment]
Changes added to the code and pull request under review.

Pull Request under review here. https://github.com/sysrich/tik/pull/27

**Comment by sysrich** [comment]
Improvements merged in v1.0.99 and later

**Comment by sysrich** [comment]
Reopened, the fixes in #27 totally broke installation

**Comment by piyr9** [comment]
I found the bug and fixed it, new pull in #31

**Comment by piyr9** [comment]
Fix #31 has been merged to main, this issue can be closed.
