### ISSUE TITLE
podman containers are not backed-up/restored

### ISSUE THREAD

**Issue by sladiri** [sysrich/tik#7]
I ran the new installer from today [link](https://download.opensuse.org/repositories/devel:/microos:/aeon:/installer/aeon/openSUSE-Aeon-Installer.x86_64.raw.xz).
Installation and backup seemed all fine, but when I wanted to start a podman container, it could not find the storage:

```
podman start mycontainer

mounting storage for container SOME_ID: stat /home/sladi/.local/share/containers/storage/btrfs/subvolumes/SOME_ID: no such file or directory
```
[tik.log](https://github.com/sysrich/tik/files/15311784/tik.log)

Edit:
I first checked just one manually created rootless container with podman. But the storage for all distrobox containers is missing too. For example, creating a new tumbleweed container fails:

 `distrobox create --name box-test-2
Creating 'box-test-2' using image registry.opensuse.org/opensuse/distrobox:latest	Error: creating container storage: creating an ID-mapped copy of layer "725d1b0be185da66172452446cb88eb3206c4ab8365f1d12874cc4270f1d357d": creating copy of template layer "725d1b0be185da66172452446cb88eb3206c4ab8365f1d12874cc4270f1d357d" with ID "7818b3878025af2db3af7759c6ce375a58fa4a6dd169372fc08681df396a3f3b": stat /home/sladi/.local/share/containers/storage/btrfs/subvolumes/725d1b0be185da66172452446cb88eb3206c4ab8365f1d12874cc4270f1d357d: no such file or directory`

Here is the podman info: 
[podman.info.txt](https://github.com/sysrich/tik/files/15312780/podman.info.txt)

**Comment by sysrich** [comment]
Addressed in https://github.com/sysrich/tik/pull/8

**Comment by sysrich** [comment]
Thank you by the way for the awesome clear report. I really appreciated it. My terse reply was only cuz this was a real pain to fix but you made it as easy as possible with the good report :)

**Comment by sladiri** [comment]
Hey, no problem, nice to hear that! I've been very busy this week so I had to cut back a little, that is all. :)
